import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

// All dot variations of redshocker33@gmail.com to mark as disabled
const disabledEmails = [
  "r.e.d.shocker33@gmail.com",
  "r.e.ds.hocker33@gmail.com",
  "r.e.dsh.ocker33@gmail.com",
  "r.e.dsho.cker33@gmail.com",
  "r.e.dshoc.ker33@gmail.com",
  "r.e.dshock.er33@gmail.com",
  "r.e.dshocke.r33@gmail.com",
  "r.e.dshocker.33@gmail.com",
  "r.e.dshocker3.3@gmail.com",
  "r.ed.s.hocker33@gmail.com",
  "r.ed.sh.ocker33@gmail.com",
  "r.ed.sho.cker33@gmail.com",
  "r.ed.shoc.ker33@gmail.com",
  "r.ed.shock.er33@gmail.com",
  "r.ed.shocke.r33@gmail.com",
  "r.ed.shocker.33@gmail.com",
  "r.ed.shocker3.3@gmail.com",
  "r.eds.h.ocker33@gmail.com",
  "r.eds.ho.cker33@gmail.com",
  "r.eds.hoc.ker33@gmail.com",
  "r.eds.hock.er33@gmail.com",
  "r.eds.hocke.r33@gmail.com",
  "r.eds.hocker.33@gmail.com",
  "r.eds.hocker3.3@gmail.com",
  "r.edsh.o.cker33@gmail.com",
  "r.edsh.oc.ker33@gmail.com",
  "r.edsh.ock.er33@gmail.com",
  "r.edsh.ocke.r33@gmail.com",
  "r.edsh.ocker.33@gmail.com",
  "r.edsh.ocker3.3@gmail.com",
  "r.edsho.c.ker33@gmail.com",
  "r.edsho.ck.er33@gmail.com",
  "r.edsho.cke.r33@gmail.com",
  "r.edsho.cker.33@gmail.com",
  "r.edsho.cker3.3@gmail.com",
  "r.edshoc.k.er33@gmail.com",
  "r.edshoc.ke.r33@gmail.com",
  "r.edshoc.ker.33@gmail.com",
  "r.edshoc.ker3.3@gmail.com",
  "r.edshock.e.r33@gmail.com",
  "r.edshock.er.33@gmail.com",
  "r.edshock.er3.3@gmail.com",
  "r.edshocke.r.33@gmail.com",
  "r.edshocke.r3.3@gmail.com",
  "r.edshocker.3.3@gmail.com",
  "re.d.s.hocker33@gmail.com",
  "re.d.sh.ocker33@gmail.com",
  "re.d.sho.cker33@gmail.com",
  "re.d.shoc.ker33@gmail.com",
  "re.d.shock.er33@gmail.com",
  "re.d.shocke.r33@gmail.com",
  "re.d.shocker.33@gmail.com",
  "re.d.shocker3.3@gmail.com",
  "re.ds.h.ocker33@gmail.com",
  "re.ds.ho.cker33@gmail.com",
  "re.ds.hoc.ker33@gmail.com",
  "re.ds.hock.er33@gmail.com",
  "re.ds.hocke.r33@gmail.com",
  "re.ds.hocker.33@gmail.com",
  "re.ds.hocker3.3@gmail.com",
  "re.dsh.o.cker33@gmail.com",
  "re.dsh.oc.ker33@gmail.com",
  "re.dsh.ock.er33@gmail.com",
  "re.dsh.ocke.r33@gmail.com",
  "re.dsh.ocker.33@gmail.com",
  "re.dsh.ocker3.3@gmail.com",
  "re.dsho.c.ker33@gmail.com",
  "re.dsho.ck.er33@gmail.com",
  "re.dsho.cke.r33@gmail.com",
  "re.dsho.cker.33@gmail.com",
  "re.dsho.cker3.3@gmail.com",
  "re.dshoc.k.er33@gmail.com",
  "re.dshoc.ke.r33@gmail.com",
  "re.dshoc.ker.33@gmail.com",
  "re.dshoc.ker3.3@gmail.com",
  "re.dshock.e.r33@gmail.com",
  "re.dshock.er.33@gmail.com",
  "re.dshock.er3.3@gmail.com",
  "re.dshocke.r.33@gmail.com",
  "re.dshocke.r3.3@gmail.com",
  "re.dshocker.3.3@gmail.com",
  "red.s.h.ocker33@gmail.com",
  "red.s.ho.cker33@gmail.com",
  "red.s.hoc.ker33@gmail.com",
  "red.s.hock.er33@gmail.com",
  "red.s.hocke.r33@gmail.com",
  "red.s.hocker.33@gmail.com",
  "red.s.hocker3.3@gmail.com",
  "red.sh.o.cker33@gmail.com",
  "red.sh.oc.ker33@gmail.com",
  "red.sh.ock.er33@gmail.com",
  "red.sh.ocke.r33@gmail.com",
  "red.sh.ocker.33@gmail.com",
  "red.sh.ocker3.3@gmail.com",
  "red.sho.c.ker33@gmail.com",
  "red.sho.ck.er33@gmail.com",
  "red.sho.cke.r33@gmail.com",
  "red.sho.cker.33@gmail.com",
  "red.sho.cker3.3@gmail.com",
  "red.shoc.k.er33@gmail.com",
  "red.shoc.ke.r33@gmail.com",
  "red.shoc.ker.33@gmail.com",
  "red.shoc.ker3.3@gmail.com",
  "red.shock.e.r33@gmail.com",
  "red.shock.er.33@gmail.com",
  "red.shock.er3.3@gmail.com",
  "red.shocke.r.33@gmail.com",
  "red.shocke.r3.3@gmail.com",
  "red.shocker.3.3@gmail.com",
  "reds.h.o.cker33@gmail.com",
  "reds.h.oc.ker33@gmail.com",
  "reds.h.ock.er33@gmail.com",
  "reds.h.ocke.r33@gmail.com",
  "reds.h.ocker.33@gmail.com",
  "reds.h.ocker3.3@gmail.com",
  "reds.ho.c.ker33@gmail.com",
  "reds.ho.ck.er33@gmail.com",
  "reds.ho.cke.r33@gmail.com",
  "reds.ho.cker.33@gmail.com",
  "reds.ho.cker3.3@gmail.com",
  "reds.hoc.k.er33@gmail.com",
  "reds.hoc.ke.r33@gmail.com",
  "reds.hoc.ker.33@gmail.com",
  "reds.hoc.ker3.3@gmail.com",
  "reds.hock.e.r33@gmail.com",
  "reds.hock.er.33@gmail.com",
  "reds.hock.er3.3@gmail.com",
  "reds.hocke.r.33@gmail.com",
  "reds.hocke.r3.3@gmail.com",
  "reds.hocker.3.3@gmail.com",
  "redsh.o.c.ker33@gmail.com",
  "redsh.o.ck.er33@gmail.com",
  "redsh.o.cke.r33@gmail.com",
  "redsh.o.cker.33@gmail.com",
  "redsh.o.cker3.3@gmail.com",
  "redsh.oc.k.er33@gmail.com",
  "redsh.oc.ke.r33@gmail.com",
  "redsh.oc.ker.33@gmail.com",
  "redsh.oc.ker3.3@gmail.com",
  "redsh.ock.e.r33@gmail.com",
  "redsh.ock.er.33@gmail.com",
  "redsh.ock.er3.3@gmail.com",
  "redsh.ocke.r.33@gmail.com",
  "redsh.ocke.r3.3@gmail.com",
  "redsh.ocker.3.3@gmail.com",
  "redsho.c.k.er33@gmail.com",
  "redsho.c.ke.r33@gmail.com",
  "redsho.c.ker.33@gmail.com",
  "redsho.c.ker3.3@gmail.com",
  "redsho.ck.e.r33@gmail.com",
  "redsho.ck.er.33@gmail.com",
  "redsho.ck.er3.3@gmail.com",
  "redsho.cke.r.33@gmail.com",
  "redsho.cke.r3.3@gmail.com",
  "redsho.cker.3.3@gmail.com",
  "redshoc.k.e.r33@gmail.com",
  "redshoc.k.er.33@gmail.com",
  "redshoc.k.er3.3@gmail.com",
  "redshoc.ke.r.33@gmail.com",
  "redshoc.ke.r3.3@gmail.com",
  "redshoc.ker.3.3@gmail.com",
  "redshock.e.r.33@gmail.com",
  "redshock.e.r3.3@gmail.com",
  "redshock.er.3.3@gmail.com",
  "redshocke.r.3.3@gmail.com",
];

async function main() {
  console.log(`Inserting ${disabledEmails.length} disabled email accounts...`);

  let inserted = 0;
  let skipped = 0;

  for (const email of disabledEmails) {
    try {
      await prisma.emailAccount.upsert({
        where: { emailAddress: email },
        update: { status: "disabled" },
        create: {
          emailAddress: email,
          status: "disabled",
        },
      });
      inserted++;
    } catch (err) {
      console.error(`Failed to insert ${email}:`, err);
      skipped++;
    }
  }

  console.log(`Done! Inserted: ${inserted}, Skipped: ${skipped}`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
